########################################
# docker-compose up -d
#
# access via:
#   ssh root@<ip> -p 50001
#
# define alias in .ssh/config:
#   Host dmod-node1
#	    User root
#	    HostName node1
#	    Port 50001
#
#  Then use dmod-node1 in runbg.
########################################

version: "3"
services:
  dmod:
    image: matthiaskoenig/dmod:latest
    ports:
      - "50001:22"
    volumes:
      - ~/.ssh/authorized_keys:/tmp/authorized_keys:ro

