#
# docker run -d -p 50001:22 --name dmod matthiaskoenig/dmod:latest

#   access via:
#   ssh root@<ip> -p 50001
#
#   define alias in .ssh/config:
#   Host dmod-node1
#	    User root
#	    HostName node1
#	    Port 50001
#
#   Than use dmod-node1 in runbg


version: "3"
services:
  dmod:
    image: matthiaskoenig/dmod:latest
    ports:
      - "50001:22"
    volumes:
      - ${HOME}/.ssh/authorized_keys:/root/.ssh/authorized_keys

