try(library(conveniencefunctions))
try(library(forcats))
try(library(stringr))
try(library(dplyr))
try(library(purrr))
try(library(readr))
try(library(tidyr))
try(library(tibble))
try(library(ggplot2))
try(library(tidyverse))
try(library(dMod))
try(library(cOde))
try(library(stats))
try(library(graphics))
try(library(grDevices))
try(library(utils))
try(library(datasets))
try(library(methods))
try(library(base))
setwd('~/metv53fit_1_folder')
rm(list = ls())

load('metv53fit.RData')
files <- list.files(pattern = '.so')
for (f in files) dyn.load(f)
.node <- 1
.runbgOutput <- try({
    mstrust(obj_data, startpars, cores = 24, parupper = upper, parlower = lower, conditions = condition_subset, fixed = fixed_pars)
})
save(.runbgOutput, file = 'metv53fit_1_result.RData')