try(library(bindrcpp))
try(library(conveniencefunctions))
try(library(magrittr))
try(library(forcats))
try(library(dplyr))
try(library(purrr))
try(library(readr))
try(library(tidyr))
try(library(tibble))
try(library(ggplot2))
try(library(tidyverse))
try(library(dMod))
try(library(cOde))
try(library(stringr))
try(library(stats))
try(library(graphics))
try(library(grDevices))
try(library(utils))
try(library(datasets))
try(library(methods))
try(library(base))
setwd('~/tmp_n9wf8_1_folder')
rm(list = ls())

load('tmp_n9wf8.RData')
files <- list.files(pattern = '.so')
for (f in files) dyn.load(f)
.node <- 1
.runbgOutput <- try({
    mstrust(obj, mypars, "test_fits", result_path = "test_fits", sd = 5, fits = 10, cores = detectFreeCores(), blather = T)
})
save(.runbgOutput, file = 'tmp_n9wf8_1_result.RData')